### ISSUE TITLE
Formula for Triangular numbers is incorrect

### ISSUE THREAD

**Issue by ckenk** [jjfiv/ds4j#1]
In the ds4j/complexity.html page the formula for Triangular numbers is implemented as below.

```
public static int sumSequence2(int n) {
    return (n * (n - 1)) / 2;
}
```

But in the Wikipedia page it is `(n * (n + 1)) / 2`

**Comment by jjfiv** [comment]
Thanks for the issue! I've clearly had this transcription error for a while.
